#!/bin/bash
set -e -o pipefail

retry_count="${1:-3}"  # Default to 3 retries if not specified
host="$(hostname --ip-address || echo '127.0.0.1')"
user="${MYSQL_USER:-root}"

args=(
	# force mysql to not use the local "mysqld.sock" (test "external" connectibility)
	-h"$host"
	-u"$user"
	-P 3306
	--silent
)

for ((i=0; i<retry_count; i++)); do
	if command -v mysqladmin &> /dev/null; then
		if mysqladmin "${args[@]}" ping > /dev/null; then
			exit 0
		fi
	else
		if select="$(echo 'SELECT 1' | mysql "${args[@]}")" && [ "$select" = '1' ]; then
			exit 0
		fi
	fi
	sleep 10
done

exit 1
