---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tomcat-web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tomcat-web
        image: assignment5acr.azurecr.io/web:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: mysql-db
        image: assignment5acr.azurecr.io/db:latest
        ports:
        - containerPort: 3306