---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tomcat-web
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-db